{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-3.4.0.aar",
          "url": "elepay-3.4.0.aar",
          "size": 1749398,
          "sha512": "1485498bf62dc1d01ba391dd861b167268e932655d86e85cde44d502044d3e5e0314a9719f5581d8ec55ca0360769cf42969da61682edb6740ae25442b9a35e7",
          "sha256": "37d2f8d67b5aa94d068532e15fb7b3cb90841bf38eaf48ab790cff48b7c88322",
          "sha1": "c26f9929534658bf520fbd57c68772914fbaa930",
          "md5": "097ca1d848ab21fc05d00e91e37b7948"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "20.11.0"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripecardscan",
          "version": {
            "requires": "20.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "text-recognition",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-3.4.0.aar",
          "url": "elepay-3.4.0.aar",
          "size": 1749398,
          "sha512": "1485498bf62dc1d01ba391dd861b167268e932655d86e85cde44d502044d3e5e0314a9719f5581d8ec55ca0360769cf42969da61682edb6740ae25442b9a35e7",
          "sha256": "37d2f8d67b5aa94d068532e15fb7b3cb90841bf38eaf48ab790cff48b7c88322",
          "sha1": "c26f9929534658bf520fbd57c68772914fbaa930",
          "md5": "097ca1d848ab21fc05d00e91e37b7948"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "elepay-3.4.0-sources.jar",
          "url": "elepay-3.4.0-sources.jar",
          "size": 342511,
          "sha512": "6c05e7acb6e40b41ad792087969d59bfd84491c7358ad87304bf1ef883c066314a3d9969b2bef14cf1987302b285eba72727e88d60c212ea5c0ee1addb9721af",
          "sha256": "a1e08096f1477a6f5fafca1c6e0c57b22d4af7c291f4272b864eea45fa43d3c5",
          "sha1": "5128ce7f3616d79b0e05a090b3e07fe15798b3d3",
          "md5": "1a2296af07233313f8040e48ebc3682b"
        }
      ]
    }
  ]
}
