{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-3.0.3.aar",
          "url": "elepay-3.0.3.aar",
          "size": 1851266,
          "sha512": "cd13d0f1346fbf8665bebfc4c9fb4abc9d6dad6043c3300a1faeb093e15705164d857b2e835881750a117f8ec9852527f8de56d4dd39db613ea7768fa0d79c7a",
          "sha256": "61decee839e1b0a34dbdbbc074e6502c7fdb3e6bc41d6cc8cbe39d9ea305f575",
          "sha1": "c4e0bd0a6b80406e730c398f900098b618126a24",
          "md5": "a1e0a73e6dc27e939740c5a91ce223cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "20.11.0"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripecardscan",
          "version": {
            "requires": "20.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "text-recognition",
          "version": {
            "requires": "16.0.0-beta6"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-3.0.3.aar",
          "url": "elepay-3.0.3.aar",
          "size": 1851266,
          "sha512": "cd13d0f1346fbf8665bebfc4c9fb4abc9d6dad6043c3300a1faeb093e15705164d857b2e835881750a117f8ec9852527f8de56d4dd39db613ea7768fa0d79c7a",
          "sha256": "61decee839e1b0a34dbdbbc074e6502c7fdb3e6bc41d6cc8cbe39d9ea305f575",
          "sha1": "c4e0bd0a6b80406e730c398f900098b618126a24",
          "md5": "a1e0a73e6dc27e939740c5a91ce223cc"
        }
      ]
    }
  ]
}
