{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "42gdi3jsifcv5cpp5dgisz3qwq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "elepay-2.2.0.aar",
          "url": "elepay-2.2.0.aar",
          "size": 2222433,
          "sha512": "c45ab1b3ccfa849dd85a0bf3d206e5b56a776047927e35f8b777e3f6f01e12c1a82eb70a414917fdee81e6cc2740683aed367ff8c1b55008c6833c2a0c1fd549",
          "sha256": "a6bbc6a5cc25c0b19897f98a1fe6176653abc6d96928788e5d7a82dc56330d7d",
          "sha1": "1b06b27ca6b54cc53fae9fd9cebff8edce71f496",
          "md5": "6ad6f79b15c42b7e4c8859a602eec45c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.2.0.aar",
          "url": "elepay-2.2.0.aar",
          "size": 2222433,
          "sha512": "c45ab1b3ccfa849dd85a0bf3d206e5b56a776047927e35f8b777e3f6f01e12c1a82eb70a414917fdee81e6cc2740683aed367ff8c1b55008c6833c2a0c1fd549",
          "sha256": "a6bbc6a5cc25c0b19897f98a1fe6176653abc6d96928788e5d7a82dc56330d7d",
          "sha1": "1b06b27ca6b54cc53fae9fd9cebff8edce71f496",
          "md5": "6ad6f79b15c42b7e4c8859a602eec45c"
        }
      ]
    }
  ]
}
