{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-3.6.0.aar",
          "url": "elepay-3.6.0.aar",
          "size": 1751025,
          "sha512": "1e972509356ebc81284e42a36d2435e9013221179916ef40041d4a96016efbb61d6d4d9c93c02e8ce6aa424e38ea1832fc2d76080d03aeb302177131ded4425c",
          "sha256": "a75384fbcf2b44dc7ec7fce26472f28894a899fa425b0a583d68c236b300fa9d",
          "sha1": "76453817dcf5fe57a093d7609e8ec7dfde20de70",
          "md5": "c283e5b147f1f32e64a59d2af046755b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "20.11.0"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripecardscan",
          "version": {
            "requires": "20.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "text-recognition",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-3.6.0.aar",
          "url": "elepay-3.6.0.aar",
          "size": 1751025,
          "sha512": "1e972509356ebc81284e42a36d2435e9013221179916ef40041d4a96016efbb61d6d4d9c93c02e8ce6aa424e38ea1832fc2d76080d03aeb302177131ded4425c",
          "sha256": "a75384fbcf2b44dc7ec7fce26472f28894a899fa425b0a583d68c236b300fa9d",
          "sha1": "76453817dcf5fe57a093d7609e8ec7dfde20de70",
          "md5": "c283e5b147f1f32e64a59d2af046755b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "elepay-3.6.0-sources.jar",
          "url": "elepay-3.6.0-sources.jar",
          "size": 342805,
          "sha512": "62f86e83908578f64f7891886fb0ea7840ffae34a165895f872031aa5f30d52a8e662b3542f8cd8600ed7c7865709bfe1b86e773904d47c349b0e834d56c95e6",
          "sha256": "2a3305dd59580e260afde1e7c7466654644277cbc7b594b6f3021ef3af213f73",
          "sha1": "ecbc3c11b25fd3fbd070a4a7c6b80efe1d3aa7f4",
          "md5": "79dd5d2c788e023fe813afa12c74f61e"
        }
      ]
    }
  ]
}
