{
  "formatVersion": "1.1",
  "component": {
    "group": "io.elepay",
    "module": "elepay-android",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.elepay",
          "module": "elepay-core",
          "version": {
            "requires": "0.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-android-0.0.8.aar",
          "url": "elepay-android-0.0.8.aar",
          "size": 24517,
          "sha512": "726a369c5e63d6cd23ce76993d3a5ddf5c92065f79a7717ffd5bf8b6704d123b5468a82e2e34c8d1bda3a2f371f96a0ca6a294d924d13a67dd84e07b06684d07",
          "sha256": "cd90572f77fda4159358dd43f91ee7b06fe525e5cfef65723798d7588f22681f",
          "sha1": "adab77a7b310790ee856ddb630affe8f358005c0",
          "md5": "0240beb3da979529ebd5c8a4d05e797b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "io.elepay",
          "module": "elepay-core",
          "version": {
            "requires": "0.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-android-0.0.8.aar",
          "url": "elepay-android-0.0.8.aar",
          "size": 24517,
          "sha512": "726a369c5e63d6cd23ce76993d3a5ddf5c92065f79a7717ffd5bf8b6704d123b5468a82e2e34c8d1bda3a2f371f96a0ca6a294d924d13a67dd84e07b06684d07",
          "sha256": "cd90572f77fda4159358dd43f91ee7b06fe525e5cfef65723798d7588f22681f",
          "sha1": "adab77a7b310790ee856ddb630affe8f358005c0",
          "md5": "0240beb3da979529ebd5c8a4d05e797b"
        }
      ]
    }
  ]
}
