{
  "formatVersion": "1.1",
  "component": {
    "group": "io.elepay",
    "module": "elepay-creditcard",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-creditcard-0.0.8.aar",
          "url": "elepay-creditcard-0.0.8.aar",
          "size": 1323803,
          "sha512": "a160a5ef24fa814b11cfa69922e1f1eb2558c24312b91dceb70ebe2f01e016f8b4f2998212f9250fe6fa3b1303089acdfd46054f0ad3df9c8ef6ce2fe9ad3b49",
          "sha256": "56cfd83f8dd985500f9cf1a720830355cad92d10a2d81b9c69d60b28f4982cb4",
          "sha1": "aa2ef94e97e093487f2f83c9a93d3fded1defec8",
          "md5": "9130816b67765e85728cb8d8e51913b5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.elepay",
          "module": "elepay-core",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-creditcard-0.0.8.aar",
          "url": "elepay-creditcard-0.0.8.aar",
          "size": 1323803,
          "sha512": "a160a5ef24fa814b11cfa69922e1f1eb2558c24312b91dceb70ebe2f01e016f8b4f2998212f9250fe6fa3b1303089acdfd46054f0ad3df9c8ef6ce2fe9ad3b49",
          "sha256": "56cfd83f8dd985500f9cf1a720830355cad92d10a2d81b9c69d60b28f4982cb4",
          "sha1": "aa2ef94e97e093487f2f83c9a93d3fded1defec8",
          "md5": "9130816b67765e85728cb8d8e51913b5"
        }
      ]
    }
  ]
}
