{
  "formatVersion": "1.1",
  "component": {
    "group": "io.elepay.android",
    "module": "elepay-core",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-core-4.0.0.aar",
          "url": "elepay-core-4.0.0.aar",
          "size": 20928,
          "sha512": "a3bdc6ccd6344910f564d90519a938d81021c31f2a30a87e0944452a12ea863d9b72f2e4e268a83ed51f9e755e46dd46803168879d15c050ac0fe5920e6a7c2a",
          "sha256": "0e10ab56c05d4a181873fc55d2438af888f777cbbd665f9eea8618263455c79a",
          "sha1": "0e4b9bafec59f2302b358dc26dec8c30aa6c475b",
          "md5": "4d9babdb17b3895d30b1962e8c77ad45"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-core-4.0.0.aar",
          "url": "elepay-core-4.0.0.aar",
          "size": 20928,
          "sha512": "a3bdc6ccd6344910f564d90519a938d81021c31f2a30a87e0944452a12ea863d9b72f2e4e268a83ed51f9e755e46dd46803168879d15c050ac0fe5920e6a7c2a",
          "sha256": "0e10ab56c05d4a181873fc55d2438af888f777cbbd665f9eea8618263455c79a",
          "sha1": "0e4b9bafec59f2302b358dc26dec8c30aa6c475b",
          "md5": "4d9babdb17b3895d30b1962e8c77ad45"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "elepay-core-4.0.0-sources.jar",
          "url": "elepay-core-4.0.0-sources.jar",
          "size": 12895,
          "sha512": "e269bdfdab9a8981a2865163b3ec0b5eddf4e5f5882cc5d308ba41574a6a1220c63ccba4e64a48f8f7a0502f398a04abf4cb27666bca558f0fd88a92d9e6a686",
          "sha256": "66ad9207bc850a543775ebb8956f2d6cc5c4179f18d021f967131783e0193908",
          "sha1": "4141e260fd76f7395b1ef5ec8e05d713f7eb96e7",
          "md5": "df2982ebc8c8c6536be78fb237161b86"
        }
      ]
    }
  ]
}
