{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "3czteu5qzfflrkpaxlwz7a2ziy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "elepay-2.1.1.aar",
          "url": "elepay-2.1.1.aar",
          "size": 2223032,
          "sha512": "d9deb3bb9e09dcff8700f32bdd77a0def007d80b5f4fa0676f328d5101074dad2a42e39e91831f084033f899bfbd8c8f3a650a01edca0ad50318f047e11d9516",
          "sha256": "42d106e40680565bc08ac89a0f2917328b48707079acd403d7ccd18df894e901",
          "sha1": "9f91f9045ae8e9717b1c42bb40ed891373e8cb9a",
          "md5": "d1df18294957dd49fc65fd00760945fd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.1.1.aar",
          "url": "elepay-2.1.1.aar",
          "size": 2223032,
          "sha512": "d9deb3bb9e09dcff8700f32bdd77a0def007d80b5f4fa0676f328d5101074dad2a42e39e91831f084033f899bfbd8c8f3a650a01edca0ad50318f047e11d9516",
          "sha256": "42d106e40680565bc08ac89a0f2917328b48707079acd403d7ccd18df894e901",
          "sha1": "9f91f9045ae8e9717b1c42bb40ed891373e8cb9a",
          "md5": "d1df18294957dd49fc65fd00760945fd"
        }
      ]
    }
  ]
}
