{
  "formatVersion": "1.1",
  "component": {
    "group": "io.elepay",
    "module": "elepay-checkout",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-checkout-0.0.8.aar",
          "url": "elepay-checkout-0.0.8.aar",
          "size": 2235,
          "sha512": "fa03144af2e6c0adceb557eb399c50cc51de2ed17f145b003d563a61f5caf0ffeb25ea687368a441fd7e8d9d654c26e9ab2cdde38c97486008d1237411cf42e7",
          "sha256": "d16bf1771ca66b49c094a5705947cf305409e9b1198b2df30e87b0065b41693f",
          "sha1": "19f391638944377ff6d4588d90446e25764a6461",
          "md5": "db15ed6a7ba45d3d4c1ff0c1ed8fa66b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.elepay",
          "module": "elepay-core",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-checkout-0.0.8.aar",
          "url": "elepay-checkout-0.0.8.aar",
          "size": 2235,
          "sha512": "fa03144af2e6c0adceb557eb399c50cc51de2ed17f145b003d563a61f5caf0ffeb25ea687368a441fd7e8d9d654c26e9ab2cdde38c97486008d1237411cf42e7",
          "sha256": "d16bf1771ca66b49c094a5705947cf305409e9b1198b2df30e87b0065b41693f",
          "sha1": "19f391638944377ff6d4588d90446e25764a6461",
          "md5": "db15ed6a7ba45d3d4c1ff0c1ed8fa66b"
        }
      ]
    }
  ]
}
