{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.8.1.aar",
          "url": "elepay-2.8.1.aar",
          "size": 1837537,
          "sha512": "0e4a94e88bf3913b978027ac1fdb00a978aa434ff2bb8665d738b18e9b5f3c54514005625893c749aa2d1955100c89b88af3870a4e07f932a5950ab8061c708d",
          "sha256": "522349256785e6d11ed5f3785dc917b9a6927d23d6bb336e399049dbff4f446b",
          "sha1": "43c9bc2e8c35074b7f81e531e865b80d7bac0020",
          "md5": "e06b19d75a00a6d565bccb8e6b8496c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.17.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.8.1.aar",
          "url": "elepay-2.8.1.aar",
          "size": 1837537,
          "sha512": "0e4a94e88bf3913b978027ac1fdb00a978aa434ff2bb8665d738b18e9b5f3c54514005625893c749aa2d1955100c89b88af3870a4e07f932a5950ab8061c708d",
          "sha256": "522349256785e6d11ed5f3785dc917b9a6927d23d6bb336e399049dbff4f446b",
          "sha1": "43c9bc2e8c35074b7f81e531e865b80d7bac0020",
          "md5": "e06b19d75a00a6d565bccb8e6b8496c2"
        }
      ]
    }
  ]
}
